<html>
 <head>            
              <h3>Bienvenidos, Alegra </h3>            
</head>
<link rel="stylesheet" href="js/extjs/resources/css/ext-all.css" type="text/css">
<script src="js/extjs/ext-all.js"></script>            
<script type="text/javascript"> 
 // creemos un array de php y pasemos el contenido en una variable javascript.
 
  <?php            
$resp = $this->Contactos[0];              
$respjson=(json_decode($resp));
?>  

var jsvar  = '<?php echo($resp); ?>';
var parsed = JSON.parse(jsvar);
var arr = [];
for(var i = 0; i < parsed.length; i++ ){
    arr[i]=  [[parsed[i].id],[parsed[i].name], [parsed[i].identification], [parsed[i].phonePrimary], [parsed[i].observations], [parsed[i].city]];
}

    Ext.require([
    		'Ext.grid.*',
    		'Ext.data.*',
    		'Ext.util.*',
    		'Ext.state.*'
		]);            
                       
    
		Ext.onReady(function() {
        var store_data = Ext.create('Ext.data.ArrayStore', {
        	fields: [
                {name: 'id'},
           	{name: 'nombre'},
           	{name: 'identificacion'},
                {name: 'telefono'},
                {name: 'observaciones'},
        	],
        	data: arr
    	});
                     

    	// Crear el grid
    var grid = Ext.create('Ext.grid.Panel', {
        store: store_data,
        width    : 150,              
        stateId: 'stateGrid',
        columns: [
            {
                text     : 'Id',
                width    : 25,                
                sortable : true,
                dataIndex: 'id'               
            },
            {
                text     : 'Nombre',
                width    : 375,                
                sortable : true,
                dataIndex: 'nombre'
            },
            {
                text     : 'Identificación',
                width    : 120,
                sortable : true,                                
                dataIndex: 'identificacion'
            },
            {
                text     : 'Teléfono 1',
                width    : 100,
                sortable : true,                     
                dataIndex: 'telefono'
            },
            {
                text     : 'Observaciones',
                width    : 400,
                sortable : true,                     
                dataIndex: 'observaciones'
            },            
            {
                xtype : 'actioncolumn',
                header : "Action",
                items : [ {
                        icon : '../imagen/delete.png',
                        tooltip : 'Enable App',
                        width : 50,
                        id:'enableAppId',
                        handler : function (grid, rowIndex) {
        }
                    }]
            }
        ],
        height: 350,
        width: 1130,
        title: 'Contactos',
        renderTo: 'gridContactos',
       listeners : {
         itemclick: function(dv, record, item, index, e) {
   var ID = record.get('id');
   alert (ID);

}  
       }


        
    });

		});

</script>
<body>     
<div id="gridContactos"/>  
</div>
</body>
</html>
